### ISSUE TITLE
Simplify container launch

### ISSUE THREAD

**Issue by cloudnautique** [objectpartners/rancher-ecr-credentials#1]
Hi, saw the tweet, and instructions to launch. It is awesome seeing users extend Rancher! I wanted to offer an alternative approach to adding the RANCHER_* env vars at run time.

If you add the following labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment

Rancher will create and add an access key pair tied to the lifecycle of the container. These keys will behave like you created them from the UI. They are scoped to the environment. Also, Rancher will set the environment variables for you as well inside the container.

**Comment by johnrengelman** [comment]
Awesome. Thanks for the tip. I'll add this soon!

**Comment by johnrengelman** [comment]
@cloudnautique - maybe not the best place but do you think something similar for AWS integration would be possible? 

I know this would be changes to Rancher Core. But some type of IAM native integration seems useful.

**Comment by cloudnautique** [comment]
The current line of thinking is that the credentials created by Rancher could be used for container identity to Vault or something like it that already handles IAM. A small service that takes credentials, validates with Rancher then updates Vault would be needed. We also need to create more role types in Rancher with more restricted permissions.

**Comment by johnrengelman** [comment]
Hmm, I haven't been able to get this to work. When I add these labels when defining the service, these environment variables don't get defined (I also checked for `CATTLE_URL`, etc.)

**Comment by johnrengelman** [comment]
I spoke to soon. In the UI, you define the label value as `true`, not `'true'`

**Comment by cloudnautique** [comment]
Sorry, did you get it to work?

**Comment by johnrengelman** [comment]
yes, but it creates the env vars `CATTLE_URL`, `CATTLE_ACCESS_KEY`, and `CATTLE_SECRET_KEY`, so I had to update the program for that.

**Comment by cloudnautique** [comment]
Ah, cattle rancher it's all the same... :)

**Comment by johnrengelman** [comment]
Updated the README with notes about labels and verified in deployment.
