### ISSUE TITLE
Support non-Rancher environment

### ISSUE THREAD

**Issue by klausenbusk** [objectpartners/rancher-ecr-credentials#11]
Hello

It would be very cool, if this tool worked with non-Rancher environment, ex CoreOS or just Docker on a normal Linux server.

Either it should be able to call `docker login` (and bind mounted `~/.docker/` or it should change `~/.docker/config.json` directly.

Regards
Kristian

**Comment by johnrengelman** [comment]
@klausenbusk thanks for the idea, but this project is specifically to provide this support to Rancher. I don't see myself adding this support in the near future.
