### ISSUE TITLE
Incoherent Logs

### ISSUE THREAD

**Issue by Shalzz** [objectpartners/rancher-ecr-credentials#13]
It works but I get the following as output:

```
11/09/2016 17:45:47 Updating ECR Credentials
11/09/2016 17:45:48 Failed to find configured registry to update for URL 361957575444.dkr.ecr.ap-southeast-1.amazonaws.com
11/09/2016 17:45:48 Successfully updated credentials 1c14 for registry 1sp12; registry address: 361957575444.dkr.ecr.ap-southeast-1.amazonaws.com
```

**Comment by Shalzz** [comment]
It seems it happens because I have both the docker registry and the AWS ECR registry added,
and https://github.com/objectpartners/rancher-ecr-credentials/blob/master/main.go#L130 prints out the ecrURL instead of the registryHost.

**Comment by johnrengelman** [comment]
Yeah, we should put a check in there to break the loop and only print that error if we didn't find an ECR registry.
