### ISSUE TITLE
Updating creds doesn't seem to complete

### ISSUE THREAD

**Issue by c-m-hunt** [objectpartners/rancher-ecr-credentials#14]
Hi

I've created my IAM user with AmazonECRPowerUser permissions along with full permissions on the repo. I've started the container with token, secret and region. It runs up fine and the following gets put in the log...

```
10/12/2016 4:25:55 PMUpdating ECR Credentials
```

There is now failure or success message (looking through the Go code (with very little Go knowledge) I think there should be one other the other).

I can confirm that putting in incorrect token, secret or region did throw an error in to the logs.

I've tried to upgrade my container with forced pull and it keeps failing. Looking at the API for the failures, 

```
"transitioning": "error",
"transitioningMessage": "Image [811771737115.dkr.ecr.eu-west-1.amazonaws.com/sprayart:latest] failed to pull: unauthorized: authentication required",
```

I can confirm that I can use the standard login with the same creds via

```
aws ecr get-login --region eu-west-1
```

Any help appreciated.

**Comment by c-m-hunt** [comment]
Additional info..... In AWS console, I can see that my key was accessed at the times in the log on ECR. Just doesn't seem to update or do anything with the response.

**Comment by johnrengelman** [comment]
Something is wrong with your configuration. Are you passing all of `AWS_REGION`, `AWS_ACCESS_KEY_ID`, and `AWS_SECRET_ACCESS_KEY` to the container? it should print a message about either updating the registry or not finding an ECR registry. If it's not, then it's likely just hanging.
Does the machine that you are running from have the ability to make an outgoing HTTP request?

I would test that the above `aws ecr get-login` command works from the machine that is running the update container.

**Comment by c-m-hunt** [comment]
Hi. Thanks for the reply.

I have passed all of the params to the container. Can confirm by looking at env vars of container.

Yes - it definitely does seem like it's hanging but I'm not sure where. 

I didn't have AWS CLI installed on the server. I have since installed and no difference. Previously I was running the `aws ecr get-login` from a different machine and using the `docker login` command from there on this server. Since installing AWS CLI, the `aws ecr get-login` works fine on this server too.

Chris

**Comment by brhenrique** [comment]
I'm having the same issue. I have two environments on Rancher. The service works fine on one of them, but hangs on the other.

**Comment by johnrengelman** [comment]
Is there anything different about your hosts? The machine that's running hte container must have internet access. If you're running a private subnet in AWS, you'll need to make sure there is a NAT Gateway configured or a NAT instance running and configured in the subnet's routing table.

I've also added some more logging in a publish of the `latest` tag today, so give that a try and see if it gives you more information.

**Comment by c-m-hunt** [comment]
Hi. My machine definitely has internet access. Running the latest gives me this exception in the logs
```

panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
        panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x7de200, 0xc82010d1f0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200d92e8)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7de200, 0xc82010d1f0)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200d8bf8, 0xc82001a0c8, 0xc8200d8d08)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820051630, 0x7fafb82fe728, 0xc82010d1f0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82006ea00, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x744d00, 0x8f10d0, 0x13, 0x839e18, 0x4, 0xc8200d9268, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x744d00, 0x8f10d0, 0x13, 0xc8200d9268, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x744d00, 0x8f10d0, 0xc82006ea00, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x83ccb8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8d0620, 0x51, 0x0, ...)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001500, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
        /go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```
Let me know if there's anything else which could help.

**Comment by johnrengelman** [comment]
@c-m-hunt sorry, had some issues with my CI build. Can you pull the new latest and run again?

**Comment by c-m-hunt** [comment]
Hi - thanks. Have done. Definitely getting further than last time now....
```
Updating ECR Credentials
Returned from AWS GetAuthorizationToken call successfully
Looking for configured registry for host 811771737115.dkr.ecr.eu-west-1.amazonaws.com
Failed to find configured registry to update for URL 811771737115.dkr.ecr.eu-west-1.amazonaws.com
```

Assume that's my issue now. Will look properly tonight. Cheers

**Comment by johnrengelman** [comment]
That indicates that you have not defined the ECR registry in Rancher's configuration for the environment this container is running in.

**Comment by c-m-hunt** [comment]
Bingo! Great - thanks for your help. So that was the problem all along? Sorry!

**Comment by johnrengelman** [comment]
Yup. This could be more clear in the readme (it's in the Notes section. "Uses the returnes URL from AWS to discover the registry in Rancher").
