### ISSUE TITLE
ability to specify registryIds for IAM instance profiles

### ISSUE THREAD

**Issue by AdamNowotny** [objectpartners/rancher-ecr-credentials#16]
We're using IAM instance profiles so specifying AWS credentials is not required, however that does not work if the the ECR registry is in a different account. There should be a way to specify what registryId should be passed to the GetAuthorizationToken call.

**Comment by johnrengelman** [comment]
Added in https://github.com/objectpartners/rancher-ecr-credentials/commit/7ac823f01d7226a2884a73dbfffbeeb570713404.

Currently available on `latest` and will be part of `1.2.0` release
