### ISSUE TITLE
Rancher Health Check

### ISSUE THREAD

**Issue by peter-marriott** [objectpartners/rancher-ecr-credentials#18]
Would it be possible to add a health check? When the node this is running on goes down the container is not restarted on another node because there isn't a port open on the container to run a health check against.

I can work around it using auto scaling groups and labels but a health check would be cleaner.

Thank you

**Comment by johnrengelman** [comment]
Yes, this is something I'll add.

**Comment by johnrengelman** [comment]
Added support in https://github.com/objectpartners/rancher-ecr-credentials/commit/436d7b03a2d55edafffe2022ebf6a6f80b55eaf8

Is available in `latest` and will be part of `1.2.0` release.
