### ISSUE TITLE
Timeout attempting to update creds

### ISSUE THREAD

**Issue by goffinf** [objectpartners/rancher-ecr-credentials#19]
I have configured my ECR registry in Rancher and can successfully pull from it.

However the ECR updater just times out ...

```
14/12/2016 18:23:46Updating ECR Credentials
14/12/2016 18:25:47Error updating ECR, RequestError: send request failed
14/12/2016 18:25:47caused by: Post https://ecr.eu-west-1.amazonaws.com/: dial tcp 54.239.35.23:443: i/o timeout
```

I configured via the catalogue and entered the required variables for ACCESS_KEY, SECRET_KEY and AWS_REGION (eu-west-1).

If I SSH to the instance that is running the container I can succesfully call

```
$ aws ecr get-login --region eu-west-1
docker login -u AWS -p AQECAHh+dS+BlNu0NxnXwowbILs115yjd+LNAZhBLZsunOxk3AAAAxkwggMVBgkqhkiG9w0BBwagggM.... -e none https://XXXXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com
```

If I curl to https://ecr.eu-west-1.amazonaws.com I can see that is can get out to the endpoint ...

```
$ curl https://ecr.eu-west-1.amazonaws.com
<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>
```

What could be wrong here ?

Kind Regards

Fraser

**Comment by goffinf** [comment]
I'm assuming that the URL that the credentials updater is trying to hit is correct, i.e.

https://ecr.eu-west-1.amazonaws.com

shouldn't be ...

https://dkr.ecr.eu-west-1.amazonaws.com

or even .....

https://123456789012.dkr.ecr.eu-west-1.amazonaws.com

**Comment by johnrengelman** [comment]
it appears that the container isn't able to reach out to the internet to call the AWS API. the `https://ecr.eu-west-1.amazonaws.com` URL is the URL for the ECR API, so it's coming from the AWS client itself.

I just pushed a new image version tagged `latest` that's using the latest release for the AWS sdk. Could you try that?

**Comment by goffinf** [comment]
Hey John,

just got back to this one. Tried the latest image but unfortunately the same result.

I also ran outside of Rancher altogether following your docs but again the log contained ..

docker logs -f ecstatic_austin
```
Updating ECR Credentials
Error updating ECR, RequestError: send request failed
caused by: Post https://ecr.eu-west-1.amazonaws.com/: dial tcp 54.239.37.8:443: i/o timeout
```
and if if do ....

```
curl https://ecr.eu-west-1.amazonaws.com

<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>
```
I assume the values passed to the container sort that out, and in any event, the curl returns immediately whereas the container waits for the HTTP request timeout.

I made sure that the local ec2-user account and root account both had a credentials file under .aws containing the aws_access_key_id and aws_secret_access_key properties.

I can successfully push and pull from the host to/from ECR repositories.

Not sure where else to look ??

**Comment by johnrengelman** [comment]
Can you possibly try a different region?

**Comment by johnrengelman** [comment]
I just tried this locally:
```
$ docker run -e CATTLE_URL=####### -e CATTLE_ACCESS_KEY=#### -e CATTLE_SECRET_KEY=#### -e AWS_ACCESS_KEY_ID=###### -e AWS_SECRET_ACCESS_KEY=#### -e AWS_REGION=eu-west-1 objectpartners/rancher-ecr-credentials
```

and that appears to work fine:
```
Updating ECR Credentials
Returned from AWS GetAuthorizationToken call successfully
Looking for configured registry for host ######.dkr.ecr.eu-west-1.amazonaws.com
Successfully updated credentials 1c2292 for registry 1sp181; registry address: #######.dkr.ecr.eu-west-1.amazonaws.com
```

The error seem to indicate that you cannot request externally from where you are running.

**Comment by goffinf** [comment]
I used exactly that command too.
I agree it appears that the endpoint seems unreachable from within the container, although I don't understand how it is that I can access ECR without problem with a direct docker pull, and even curl shows that the endpoint *is* reached. That's still hitting the same HTTP endpoint isn't it ?

Could it be proxy settings inside the container ?

For the CATTLE_ACCESS_KEY I used a global API one, is that correct ?

**Comment by johnrengelman** [comment]
No, you should use an Environment API key since registries are linked to environments.
If you use a global key, then `CATTLE_URL` is required to be the path to a specific environment (e.g. http://rancher.company.com:8080/v1/project/1a15)

**Comment by johnrengelman** [comment]
There are no proxy settings in the container. There's many things that could be problematic here, but it's pretty evident that it's a configure on your systems and not the container image itself (since the same image is run effectively on many, many systems).

Are you trying to do this on your local development machine? What OS are you running? (if it's Mac are you using Docker for Mac or the old Boot2Docker)? If this is a deployed machine, what's the OS? How is Docker installed on that machine? What version of Docker?

**Comment by goffinf** [comment]
Ok, makes sense it's an Env level access key, I'll change that and try again.

Yes I'm sure you are right that it's specific to my set up. Here are the details ..

RHEL 7.3
AWS
Docker 1.12.5
docker-compose 1.9.0
Rancher v1.3.0

Docker is installed as part of our packer AMI build for docker, it's a build process we have been using for more than 12 months successfully. ECR is new to us though, previously we just used our own private registry using the standard docker registry image, backed by S3, and that has actually been pretty rock solid, but company policy has changed so ECR it is !

I also have the Amazon ecr-credentials-helper binary installed which removes the need to generate the ECR login password or call docker login when SSH'd locally (albeit that is not encouraged), and that works perfectly in the sense that I have never had to generate a new password for any docker pull from ECR. See here: 
https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/

These instances do have some significant hardening. They are based form the Amazon CIS image for RHEL and we apply additional security software, in our case Trend Deep Security Agent which covers off IPS and AV amongst other things. This has caused a few issues for us in other network use cases but it's hard to see how it could play any part here TBH.

Don't know if any of that shines a light on something obvious ?

Thanks for your continued help

Fraser.

**Comment by goffinf** [comment]
Tried with Env API values. No change.

This is what a simple curl looks like ?

$ curl -v https://ecr.eu-west-1.amazonaws.com

* About to connect() to proxy management-proxy.nonprod.management.aws-euw1-services.com port 80 (#0)

*   Trying 10.63.10.164...

* Connected to management-proxy.nonprod.management.aws-euw1-services.com (10.63.10.164) port 80 (#0)

* Establish HTTP proxy tunnel to ecr.eu-west-1.amazonaws.com:443

> CONNECT ecr.eu-west-1.amazonaws.com:443 HTTP/1.1
> Host: ecr.eu-west-1.amazonaws.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
> 

< HTTP/1.1 200 Connection established

< 

* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt

  CApath: none

* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

* Server certificate:

*       subject: CN=ecr.eu-west-1.amazonaws.com,O="Amazon.com, Inc.",L=Seattle,ST=Washington,C=US

*       start date: Dec 28 00:00:00 2016 GMT
*       expire date: Jan 26 23:59:59 2018 GMT
*       common name: ecr.eu-west-1.amazonaws.com
*       issuer: CN=Symantec Class 3 Secure Server CA - G4,OU=Symantec Trust Network,O=Symantec Corporation,C=US

> GET / HTTP/1.1

> User-Agent: curl/7.29.0

> Host: ecr.eu-west-1.amazonaws.com

> Accept: */*> 

< HTTP/1.1 403 Forbidden

< Server: Server
< Date: Thu, 12 Jan 2017 23:56:47 GMT
< Content-Type: null
< Content-Length: 127
< Connection: keep-alive
< x-amzn-RequestId: c74d0e88-d922-11e6-ab18-998ca4caa771<

<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>

**********************************************************************

**Comment by johnrengelman** [comment]
I would try running that `curl` command from within the ecr-credential container or any docker container for that matter.
`docker exec -it <ecr-credential-updater container id> /bin/bash` and then run your curl command.

It appears that your system is using a HTTP proxy to establish outgoing connections. I suspect this information needs to be configured inside the docker container as well. You can use the `HTTP_PROXY` envvar as defined here to configure the HTTP proxy settings - https://golang.org/pkg/net/http/#ProxyFromEnvironment

**Comment by goffinf** [comment]
Hey John,

If I set my host's http_proxy, https_proxy and no_proxy values inside the container everything appears to work nicely.

Do you think you could provide an updated image that would allow me to pass those as environment variables with docker run ? .... unless you know another way of injecting them in at launch time ?

**Comment by johnrengelman** [comment]
Have you tried setting the HTTP_PROXY envvar on the container with the appropriate information? 
I linked to the documents in my previous comment. That will propagate to the program itself.

The great thing of Docker is that you can use this as a starting point and add your own customizations. I'm not going to including customized behavior in this image.
