### ISSUE TITLE
ECR registry details not updating

### ISSUE THREAD

**Issue by bobjana** [objectpartners/rancher-ecr-credentials#2]
The only output from container log: 
_2016-02-10 09:58:11.851356155 +0000 UTC] Updating ECR Credentials_

Docker command:

_docker run -d -e AWS_REGION=us-east-1 -e AWS_ACCESS_KEY_ID=xxx -e AWS_SECRET_ACCESS_KEY=xxx -e CATTLE_URL=http://<host>/v1/projects/1a10 -e CATTLE_ACCESS_KEY=xxx -e CATTLE_SECRET_KEY=xxx  objectpartners/rancher-ecr-credentials:latest_

Rancher env:

Rancher	v0.56.1
Cattle	v0.141.1
User Interface	v0.86.0
Rancher Compose	v0.7.1

**Comment by johnrengelman** [comment]
This might be the case if the registry URL you entered in Rancher started with `http://` or `https://`
This should be fixed in 1.0.0.
Can you try running that version?

**Comment by johnrengelman** [comment]
I've just released a `1.0.1` version, so please try that and let me know if you are still having a problem.
Going to close this ticket for now.

**Comment by bobjana** [comment]
Hi John,

Apologies for the late feedback. I deployed version 1.0.1 & got further
however a new "error" popped up:

Checking: https://#########.dkr.ecr.us-east-1.amazonaws.com
Checking registry: #########.dkr.ecr.us-east-1.amazonaws.com against:
#########.dkr.ecr.us-east-1.amazonaws.com
*Failed to update registry credential 1c18, Resource type
[registryCredential] is not updatable*

Not entirely sure whether it's a setting a need to configure on the ecr
side or a parameter I'm missing/misconfigured on ecr-container.

Thanks for the work you done on this container - I hope it gets
incorporated into rancher base in some shape or form.

Regards,
Dylan

**Comment by johnrengelman** [comment]
Open a new ticket please. 
Also include which version of Rancher you are running.
