### ISSUE TITLE
Failed to update registry credential 1c37, Resource type [registryCredential] is not updatable

### ISSUE THREAD

**Issue by OniReimu** [objectpartners/rancher-ecr-credentials#20]
Rancher V1.2
objectpartners/rancher-ecr-credentials:1.1.0

Got a failure shown as follows,
Updating ECR Credentials
Failed to update registry credential 1c37, Resource type [registryCredential] is not updatable

I am not sure if i was missing something...

**Comment by johnrengelman** [comment]
I've seen this reported before - https://github.com/objectpartners/rancher-ecr-credentials/issues/5.

Can you verify that you have the appropriate lables configured on the service? https://github.com/rancher/community-catalog/blob/master/templates/ecr/2/docker-compose.yml#L8-L9

Otherwise you have to set the `CATTLE_` envvars per the README.

**Comment by OniReimu** [comment]
ECRCredentials:
  environment:
    AWS_REGION: ${AWS_REGION}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    CATTLE_URL: ${CATTLE_URL}
    CATTLE_ACCESS_KEY: ${CATTLE_ACCESS_KEY}
    CATTLE_SECRET_KEY: ${CATTLE_SECRET_KEY}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  tty: true
  image: objectpartners/rancher-ecr-credentials
  stdin_open: true

The above was my scripts. I followed the steps shown in http://rancher.com/using-amazon-container-registry-service/, plus CATTLE_URL, CATTLE_ACCESS_KEY and CATTLE_SECRET. I dont think I missed out something...

**Comment by johnrengelman** [comment]
And you've define the registry in Rancher for the environment that this container is running in?

**Comment by OniReimu** [comment]
i actually directly type in my key and secret in the scripts instead of  using ${}.

**Comment by OniReimu** [comment]
yes i've defined my ecr already

**Comment by johnrengelman** [comment]
@OniReimu ok, i think I know the problem here - are you passing global credentials to your container?
If so, that won't work unless you change the CATTLE_URL to point to a specific environment (http://my-rancher.domain.com/v1/project/<id>)

**Comment by johnrengelman** [comment]
and if you're running on the rancher cluster, you dont' need to explictly pass the `CATTLE_` envvars to the container. Rancher will auto assign them for the environment that it is running in.

**Comment by OniReimu** [comment]
thank you, it works when i replaced the global key with an env key.
