### ISSUE TITLE
Ability to use `environment{}` block variables from Terraform rancher_stack resource

### ISSUE THREAD

**Issue by arsdehnel** [objectpartners/rancher-ecr-credentials#24]
I was trying to set this up in a stack using the [Rancher Stack](https://www.terraform.io/docs/providers/rancher/r/stack.html) resource from Terraform.  It appears that using the `environment{}` block in this is not working as a place to put the environment variables listed on the readme of this repo.  This would be lovely if it works (and maybe I'm just doing something wrong) as it feels more Terraform-y and allows variables in here without the extra configuration of a `template_file` input for the `docker_compose`.  Not that it couldn't be done that way but thought I'd check on the feasibility of using the `environment{}` block. 

Here is what I have setup:

```
resource "rancher_stack" "ecr_credentials_updater" {
  name = "ecr-credentials-updater"
  environment_id = "${module.devops_env.environment_id}"
  docker_compose = <<EOF
ecr-updater:
  environment:
    AWS_REGION: us-west-2
    AWS_ROLE_ARN: <copy and pasted my arn here>
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
  tty: true
  image: objectpartners/rancher-ecr-credentials:1.2.0
  stdin_open: true
EOF

  rancher_compose = <<EOF
ecr-updater:
  scale: 1
EOF

  environment {
    AWS_REGION = "us-west-2"
    AWS_ROLE_ARN = "${aws_iam_role.rancher_ecr_role.arn}"
  }

}
```

I left the `environment{}` block in there but it doesn't seem to be working, the logs show this when I remove the `environment:` block from the `docker_compose` yaml:

```
3/27/2017 8:27:02 AM2017/03/27 13:27:02 [main] Updating ECR Credentials
3/27/2017 8:27:02 AM2017/03/27 13:27:02 [updateEcr] Error calling AWS API: MissingRegion: could not find region configuration
3/27/2017 8:27:02 AM2017/03/27 13:27:02 [healthcheck] Starting Healthcheck listener at :8080/ping
```

**Comment by johnrengelman** [comment]
those `environments` are different things.
The `environment` block in the Terraform stack resources is not for setting environment variables, it's for passing the answers for a stack template.
