### ISSUE TITLE
Fail to update credentials when CATTLE_URL is SSL with self-signed certificate

### ISSUE THREAD

**Issue by lekum** [objectpartners/rancher-ecr-credentials#8]
Hi,

I have deployed a rancher v.1.0.2 environment with HA and SSL, with a self-signed certificate generated by the rancher GUI itself.

When running the `rancher-ecr-credentials`, it fails with this message:

```
Failed to create rancher client: Get https://my-cattle-url/v1: x509: certificate signed by unknown authority
```

Maybe there is an option to create a Rancher Client without SSL verification?

Thanks!

**Comment by johnrengelman** [comment]
hmmm. interesting issue. The real goal would be to have some way to include the self-signed cert into the cert store for this client rather than just disabling verification (though I could be persuaded to include a config option to disable verification)

**Comment by lekum** [comment]
Hi,

Recently I have upgraded Rancher server to 1.1.2 and the catalog version of the ECR credentials updater works again. Probably the have re-written parts regarding SSL in HA.

Thanks!
